### ISSUE TITLE
undefined: strings.Builder while building client-go -- golang 1.10 or higher is required

### ISSUE THREAD

**Issue by dove-young** [istio/istio#9394]
**Describe the bug**

Building Istio hit this error
```
# istio.io/istio/vendor/k8s.io/client-go/transport
vendor/k8s.io/client-go/transport/round_trippers.go:437:9: undefined: strings.Builder
make: *** [pilot-discovery] Error 2
```
According to client-go issue https://github.com/kubernetes/client-go/issues/449 , this was fixed by update golang to 1.10 or higher.  

And Istio dev wiki mentioned that `Istio currently builds with Go 1.9`. That is not correct so far. 

https://github.com/istio/istio/wiki/Dev-Guide

I did not reproduce this problem by building with Golang 1.11. 

**Expected behavior**

Istio dev wiki need to modify Golang version to 1.10 or higher. Better to 1.11 or higher.

**Steps to reproduce the bug**
- Check out latest code in master branch
- cd `istio` dir,  try `make`

**Version**
Git HEAD is `7dc2542`

**Installation**

**Environment**

CentOS 7.5

**Cluster state**
