### ISSUE TITLE
Bookinfo ratings-v2 with MongoDB is broken

### ISSUE THREAD

**Issue by luksa** [istio/istio#34205]
**Bug description**
Ratings v2 with MongoDB always fails with the following error:

```
TypeError: db.collection is not a function
    at /opt/microservices/ratings.js:147:14
    at /opt/microservices/node_modules/mongodb/lib/utils.js:693:5
    at /opt/microservices/node_modules/mongodb/lib/mongo_client.js:227:7
    at connectCallback (/opt/microservices/node_modules/mongodb/lib/operations/connect.js:366:5)
    at /opt/microservices/node_modules/mongodb/lib/operations/connect.js:459:5
    at Server.connectHandler (/opt/microservices/node_modules/mongodb/lib/topologies/server.js:291:9)
    at Object.onceWrapper (events.js:422:26)
    at Server.emit (events.js:315:20)
    at Pool.<anonymous> (/opt/microservices/node_modules/mongodb/lib/core/topologies/server.js:384:12)
    at Pool.emit (events.js:315:20)
```

This has been broken since https://github.com/istio/istio/pull/26427, when MongoDB was upgraded from 2.2 to 3.6. The MongoDB client API changed, but the code in ratings.js was never updated.

**Affected product area (please put an X in all that apply)**

[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Steps to reproduce the bug**
1. Deploy ratings-v2 with MongoDB
2. Send request to ratings-v2
3. Check the ratings-v2 log

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
Istio 1.7+
