### ISSUE TITLE
503 during VirtualService update in 1.8

### ISSUE THREAD

**Issue by arturenault** [istio/istio#29310]
**Bug description**
We're trying to upgrade knative to Istio 1.8, but are running into issues (knative/net-istio#426). We have a test that creates a VirtualService, then updates it 10 times to return different headers. We usually run 10 of these tests in parallel.

After updating to 1.8, I consistently see 503s between updates. [ingress-conformance-0-update-bflpksfb] and [ingress-conformance-0-update-jwnqvzhi] reflect the headers in the response; as below. The outage happens when the header gets applied.

```
    update.go:191: [ingress-conformance-10-update-bxlqwtjl] Got OK status!
    util.go:975: Error meeting response expectations for "http://ingress-conformance-10-update-uvnvrjow.example.com": got unexpected status: 503, expected map[200:{}]
    util.go:975: HTTP/1.1 503 Service Unavailable
        Date: Tue, 01 Dec 2020 21:04:57 GMT
        Server: istio-envoy
        Content-Length: 0
        
    update.go:191: [ingress-conformance-10-update-xuzhueaw] Got OK status! 
 ```

Envoy's logs point to there not being a route during this time, which is odd:

```
[2020-12-01T21:04:57.972Z] "GET / HTTP/1.1" 503 NR "-" 0 0 0 - "10.128.0.39" "knative.dev/TestIngressConformance/10/update/ingress-conformance-10-update-gouiithw" "e27c8599-d973-4d80-876d-4838ac4e0523" "ingress-conformance-10-update-uvnvrjow.example.com" "-" - - 10.8.0.7:8080 10.128.0.39:23011 - -
```

Recently

[ ] Docs
[ ] Installation
[X] Networking
[X] Performance and Scalability
[ ] Extensions and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure
[ ] Upgrade

**Expected behavior**
VirtualService should stay available between updates.

**Version** (include the output of `istioctl version --remote` and `kubectl version --short` and `helm version --short` if you used Helm)
```
client version: 1.7.2
control plane version: 1.8.0
data plane version: 1.8.0 (1 proxies)
```

**How was Istio installed?**
Latest 1.8 using istioctl with the following config:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt
    pilot:
      autoscaleMin: 3
      autoscaleMax: 10
      cpu:
        targetAverageUtilization: 60
    gateways:
      istio-ingressgateway:
        autoscaleMin: 2
        autoscaleMax: 5

  addonComponents:
    pilot:
      enabled: true

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            limits:
              cpu: 3000m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
```

**Environment where the bug was observed (cloud vendor, OS, etc)**
GKE

**Comment by howardjohn** [comment]
@arturenault so the test is essentially doing:

1. Create VS with header match `foo: bar-1`
2. curl -H "foo: bar-1"
3. Edit VS with header match `foo: bar-2`
4. curl -H "foo: bar-2"

And step (4) is getting a 503?

if so that seems expected since there may be a race between the new VS config being propagated. Maybe it looks more like


1. Create VS with header match `foo: bar-1`
2. curl -H "foo: bar-1"
3. Edit VS with header match `foo: bar-2`
4. Prober: curl -H "foo: bar-2" until it returns 200
5. After prober success, run `curl -H "foo: bar-2"` again, and it 503s

Let me know if either of those are accurate

**Comment by arturenault** [comment]
Sorry, we're updating the *set* headers (`spec.http.route.headers.request.set`), not the header match. Otherwise it does look like 1.

**Comment by howardjohn** [comment]
ah, got it. That certainly shouldn't happen then. Thanks

**Comment by howardjohn** [comment]
```
for i in {0..100}; do
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: echo
  namespace: default
spec:
  gateways:
  - echo
  hosts:
  - '*'
  http:
  - headers:
      request:
        set:
          foo: bar-$i
    route:
    - destination:
        host: echo
        port:
          number: 8080
      headers:
        request:
          set:
            other: baz-$i
EOF
sleep 1
done

```

I tried reproducing by running ^ and send a bunch of requests; no luck. I must be doing something differently than knative if you are able to consistently hit this with the test

**Comment by arturenault** [comment]
It might require doing this in parallel with a few different VirtualServices. The test creates 10 VSes in parallel and updates each of them 10 times. When I change the test to just create one and update it things succeed. I'll play around and see if I can get a knative-less repro as well

**Comment by arturenault** [comment]
It looks like I misunderstood what the test was doing, sorry for the confusion.

At first we create a k8s service and a virtualservice.

The first verification we do is update the VS's header as described above and make sure we get a 200. We do this 10 times.

Then, we create a new k8s service and pod at each iteration, wait for them to be ready, and then update the VS to point to them. We do this 10 times too. This is the stage at which we're getting 503s; in almost every test run I've done I've hit this at least once.

Is this expected in any way in 1.8? We have this as a knative conformance test and it was passing before.

**Comment by howardjohn** [comment]
@arturenault at any point is there two services pointing to the same pod? If so it might be fixed in 1.8.1 by https://github.com/istio/istio/pull/29333

Whatever it is, its certainly not expected

**Comment by arturenault** [comment]
It doesn't look like we ever have two services pointing at the same pod, at least not the ones we create for the test since we use randomly generated names for those.

**Comment by howardjohn** [comment]
It would be based on the label selector I think. I have had problems running knative e2e tests in the past, it would be great to have a non-knative reproducer if possible

**Comment by arturenault** [comment]
Correct, the label selector is the randomly generated test name.

I'll try to create a non-knative repro when I have some time; if you want to check out the knative repro in the meantime this is the test I'm running:

`go test ./test/conformance -count=1 -tags=e2e -v -run TestIngressConformance/^0$/update`

**Comment by arturenault** [comment]
OK, I have a repro!

1. Create 12 pods and services, each listening on its own port:
```
for i in {20000..20012}; do export i
envsubst < pod.yaml | kubectl apply -f - ; envsubst < service.yaml | kubectl apply -f -
done
```

2. Repeatedly update virtual service to point at different services:
```
for i in {20000..20012}; do export i
envsubst < vs.yaml | k apply -f -
done
```

3. Meanwhile make a bunch of curl requests:
```
while :
do
curl -s http://<istio-ingressgateway-ip>:80/ -HHost:ingress-conformance.example.com -I | tee -a reqlogs.log
done
```

YAMLs below:
pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test-pod: ingress-conformance-$i
  name: ingress-conformance-$i
spec:
  containers:
  - env:
    - name: PORT
      value: "$i"
    image: gcr.io/knative-samples/helloworld-go
    name: foo
    ports:
    - containerPort: $i
      name: http
      protocol: TCP
```

service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: ingress-conformance-$i
spec:
  ports:
  - name: http
    port: $i
    protocol: TCP
    targetPort: $i
  selector:
    test-pod: ingress-conformance-$i
  sessionAffinity: None
  type: ClusterIP
```

vs.yaml
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ingress-conformance
spec:
  gateways:
  - knative-serving/knative-ingress-gateway
  hosts:
  - ingress-conformance.example.com
  http:
  - route:
    - destination:
        host: ingress-conformance-$i.default.svc.cluster.local
        port:
          number: $i
      headers:
        respons:
          set:
            Who-Are-You: ingress-conformance-$i
```

knative-ingress-gateway just looks like this:
```
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: devel
  name: knative-ingress-gateway
  namespace: knative-serving
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: 80
      protocol: HTTP
```

**Comment by howardjohn** [comment]
Thank you! I reproduced it, looking into it now

**Comment by howardjohn** [comment]
This is fixed in https://github.com/istio/istio/pull/29060. Basically we accidentally enabled a feature in 1.8 due to a merge conflict when it wasn't ready. Its fixed in 1.8.1 (as tested by 100 iterations of the above reproducer). https://github.com/istio/istio/issues/29131 tracks the re-enablement of this feature and marks fixing this as a blocker.

The root cause is the feature will filter out clusters we don't need in the gateway. However, when we get the new VS we then send the cluster and route referncing the cluster to envoy at the same time. There is a race here if the route is applied before the cluster.

**Comment by arturenault** [comment]
Thanks for looking into it. So is a fix expected in 1.8.1?

**Comment by howardjohn** [comment]
Yes which is expected very soon - afaik tomorrow

**Comment by arturenault** [comment]
Confirmed that 1.8.1 fixed the issue. Thanks for looking into this!

**Comment by linsun** [comment]
Note: while this issue is fixed in 1.8 by dark launch PILOT_FILTER_GATEWAY_CLUSTER_CONFIG, the original issue introduced by the PILOT_FILTER_GATEWAY_CLUSTER_CONFIG feature still exist, as John mentioned: https://github.com/istio/istio/issues/29310#issuecomment-740224564

**Comment by linsun** [comment]
reopen to avoid confusion that this is fixed... only fixed when the PILOT_FILTER_GATEWAY_CLUSTER_CONFIG feature is disabled.

**Comment by howardjohn** [comment]
flag issues are tracked in https://github.com/istio/istio/issues/29131
