### ISSUE TITLE
Compile error on GCC >8.1 "clearing an object of non-trivial type"

### ISSUE THREAD

**Issue by Meai** [istio/istio#15727]
https://github.com/istio/proxy/blob/master/src/envoy/utils/stats.cc#L39

`memset(&old_stats_, 0, sizeof(old_stats_));`

this doesn't compile on GCC 8.1

```
external/istio_proxy/src/envoy/utils/stats.cc: In constructor 'Envoy::Utils::MixerStatsObject::MixerStatsObject(Envoy::Event::Dispatcher&, Envoy::Utils::MixerFilterStats&, google::protobuf::Duration, Envoy::Utils::GetStatsFunc)':
external/istio_proxy/src/envoy/utils/stats.cc:39:44: error: 'void* memset(void*, int, size_t)' clearing an object of non-trivial type 'struct istio::mixerclient::Statistics'; use assignment or value-initialization instead [-Werror=class-memaccess]
   memset(&old_stats_, 0, sizeof(old_stats_));
                                            ^
In file included from external/istio_proxy/src/envoy/utils/stats.h:21,
                 from external/istio_proxy/src/envoy/utils/stats.cc:18:
external/istio_proxy/include/istio/mixerclient/client.h:54:8: note: 'struct istio::mixerclient::Statistics' declared here
 struct Statistics {
        ^
```
