### PR TITLE
Lint fixups in master

### PR DESCRIPTION
**Pull request by awwithro**
Introduced in https://github.com/istio/istio/pull/3368
```
mixer/adapter/dogstatsd/dogstatsd.go:150:2:error: should write info := h.metrics[mname] instead of info, _ := h.metrics[mname] (S1005) (megacheck)
mixer/adapter/dogstatsd/dogstatsd.go:51:2:error: this value of client is never used (SA4006) (megacheck)
mixer/adapter/dogstatsd/dogstatsd.go:101:14:error: error return value not checked (ce.Appendf("metricName", "%s is a valid metric but is not configured to be handled by the datadog adapter", mname)) (errcheck)
mixer/adapter/dogstatsd/dogstatsd_test.go:225:12:error: this value of err is never used (SA4006) (megacheck)
```

### CODE REVIEW

**Comment by ldemailly** [comment]
/lgtm
thx!

**Comment by ldemailly** [comment]
merging this as linter (which was broken) + tests passed - master is broken without this pr

**Comment by ldemailly** [comment]
thanks for the quick fix @awwithro  - the reason it broke is related to #3471
