### ISSUE TITLE
mixer e2e TestRateLimit fails on postsubmit

### ISSUE THREAD

**Issue by jmuk** [istio/istio#2128]
Two consecutive e2e runs (for both rbac-auth and rbac-no_auth) failed for the same reason. Could be a flake, but suspecting this is a consistent test failure. The failed test was mixer's `TestRateLimit`, and the error message was like
```
I1213 04:55:35.403] --- FAIL: TestRateLimit (173.46s)
I1213 04:55:35.403] 	mixer_test.go:469: Establishing metrics baseline for test...
I1213 04:55:35.403] 	mixer_test.go:471: prometheus query: istio_request_count{destination_service="ratings.mixer-test-51660f11c07f4e9ba25d7c32ec.svc.cluster.local"}
I1213 04:55:35.403] 	mixer_test.go:479: error getting prior 429s, using 0 as value (msg: value not found for map[string]string{"response_code":"429"})
I1213 04:55:35.403] 	mixer_test.go:488: Baseline established: prior200s = 1.000000, prior429s = 0.000000
I1213 04:55:35.403] 	mixer_test.go:490: Sending traffic...
I1213 04:55:35.404] 	mixer_test.go:519: Fortio Summary: 600 reqs (9.964231 rps, 600.000000 200s (9.964231 rps), 0 400s)
I1213 04:55:35.404] 	mixer_test.go:531: Expected Totals: 200s: 60.000000 (0.996423 rps), 429s: 540.000000 (8.967808 rps)
I1213 04:55:35.404] 	mixer_test.go:542: prometheus query: istio_request_count{destination_service="ratings.mixer-test-51660f
```
(from https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-no_auth/195/)

This started from https://github.com/istio/istio/commit/ebadf857d1b633744e5d17bde5fe5f5207691a42, and I am not sure if proxy update can cause errors like this.

**Comment by qiwzhang** [comment]
I am working on the fix.  Hope this PR will fix it
https://github.com/istio/istio/pull/2117

**Comment by jmuk** [comment]
Seems still broken after #2117. Is https://github.com/istio/istio/pull/2130 also necessary?

**Comment by qiwzhang** [comment]
Yes.

**Comment by jmuk** [comment]
Still failed even after #2130? (see https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-auth/205/ and https://k8s-gubernator.appspot.com/build/istio-prow/e2e-suite-rbac-no_auth/205/)

**Comment by jmuk** [comment]
Seems fixed now. Thank you!
