### ISSUE TITLE
Issues when upgrading from istio 1.11.4 to 1.12.5

### ISSUE THREAD

**Issue by Caaslund** [istio/istio#38046]
### Bug Description

When attempting to upgrade from istio 1.11.4 to istio 1.12.5 using an istio-operator container, I run into an error where the operator fails out when processing `charts/base/templates/default.yaml`, as .Values.defaultRevision is not set in our values file for istio-1.11.4 (as that field is not defined), but as a result, interpretation of lines such as `{{ .Values.defaultRevision }}` fail. Without editing chart files to remove this defaultRevision behavior, is there a way we could make the upgrade process work from 1.11.4 to 1.12.5?

### Version

```prose
(istioctl not included since we are doing an istio-operator image based installation)
$ kubectl version --short
Client Version: v1.21.1
Server Version: v1.22.6
$ helm version --short
v3.3.4+ga61ce56
```

### Additional Information

Here is the file with the interpretation code causing issues: [https://github.com/istio/istio/blob/1.12.5/manifests/charts/base/templates/default.yaml](https://github.com/istio/istio/blob/1.12.5/manifests/charts/base/templates/default.yaml)

And here are the logs in our istio-operator pod demonstrating the issue:
```2022-03-16T19:03:39.593584Z	error	Error rendering the manifest: template: base/templates/default.yaml:1:12: executing "base/templates/default.yaml" at <eq .Values.defaultRevision "">: error calling eq: incompatible types for comparison
2022-03-16T19:03:44.787911Z	info	installer	Applying Kubernetes overlay: 
- kind: Deployment
  name: istiod
  patches:
  - path: spec.template.spec.dnsConfig
    value:
      options:
      - name: single-request-reopen```
